### ISSUE TITLE
Evilnginx starts in developer mode

### ISSUE THREAD

**Issue by aic0n** [thirdbyte/pacu#1]
First of all great project!

I tried setting this up but when I enter the tmux session of evilgnix, I realised it starts in developer mode. Can you help with that?

**Comment by thirdbyte** [comment]
@aic0n The reason for starting Evilginx in developer mode is to use self signed certificates instead of generating them using Let's Encrypt. PACU is intended to be put behind some kind of reverse proxy hosted on a separate infrastructure like Cloudflare, Cloudfront, etc. So ideally, the target facing proxy/CDN needs to take care of SSL/TLS.
